AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  DataLifecycleManager:
    Type: "AWS::DLM::LifecyclePolicy"
    Properties:
      Description: "DLM Policy"
      State: "ENABLED"
      ExecutionRoleArn:
        Fn::Join:
          - ""
          -
            - "arn:aws:iam::"
            - Ref: "AWS::AccountId"
            - ":role/AWSDataLifecycleManagerDefaultRole"
      PolicyDetails:
        ResourceTypes:
          - "INSTANCE"
        TargetTags:
          - Key: ""
            Value: ""
        Schedules:
          - Name: "Snapshot Schedule"
            TagsToAdd: []
            CreateRule:
              Interval: 24
              IntervalUnit: "HOURS"
              Times:
                - "00:00"
            RetainRule:
              Count: 3
            CopyTags: true
Parameters: {}
Metadata: {}
Conditions: {}