Parameters:
  EmailAddress:
      Description: Email Address for sending SNS notifications for CodeCommit
      Type: String
      Default: pawanrai852@gmail.com
  TagKey:
      Type: String
      Default: Name
      Description: >-
        The tag name that is associated with EC2 instances on which CodeDeploy
        agent is installed
  TagValue:
      Description: The tag value that identifies this as a target for deployments.
      Type: String
      Default: CodeDeployEC2Tag
      AllowedPattern: '[\x20-\x7E]*'
      ConstraintDescription: Can contain only ASCII characters.
  EC2KeyPairName:
      Description: >-
        Name of an existing Amazon EC2 key pair to enable SSH access to the
        instances.
      Type: 'AWS::EC2::KeyPair::KeyName'
      MinLength: '1'
      MaxLength: '255'
      Default: cloudFormationKeyPair
      AllowedPattern: '[\x20-\x7E]*'
      ConstraintDescription: Can contain only ASCII characters.
Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: Dynamic Configuration
          Parameters:
            - EC2KeyPairName
      ParameterLabels:
        EC2KeyPairName:
          default: EC2 KeyPair Name
        RepositoryName:
          default: CodeCommit Repository Name
Resources:
  ArtifactStore:
    Type: "AWS::S3::Bucket"
    Properties: 
      VersioningConfiguration:
        Status: Enabled
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
            Version: 2012-10-17
  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'codestar-connections:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'codecommit:GetBranch'
                  - 'codecommit:GetCommit'
                  - 'codecommit:UploadArchive'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:CancelUploadArchive'
                  - 'codebuild:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                  - 'arn:aws:s3:::elasticbeanstalk*'
                Effect: Allow
              - Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                  - 'iam:PassRole'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                Resource: '*'
                Effect: Allow
            Version: 2012-10-17
  CodeBuildJavaProject:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Name:
        Ref: AWS::StackName
      Description: Build Java application
      ServiceRole:
        Fn::GetAtt:
        - CodeBuildRole
        - Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
      Source:
        Location: https://github.com/pawanrai852/CodeDeployRepository
        Type: GITHUB
      TimeoutInMinutes: 10
      Tags:
      - Key: Owner
        Value: JavaTomcatProject
  MySNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
  TestingNameCodeDeploy:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://ec2bucketinindia.s3.amazonaws.com/FinalDraftForEC2CFCodePipelineV2.yml
      TimeoutInMinutes: '60'
      Parameters:
        TagValue: !Ref TagValue
        KeyPairName: !Ref EC2KeyPairName
  TestingAppName:
    Type: 'AWS::CodeDeploy::Application'
    DependsOn: TestingNameCodeDeploy
  TestingAppGroupName:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    DependsOn: TestingAppName
    Properties:
      ApplicationName: !Ref TestingAppName
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Key: !Ref TagKey
          Value: !Ref TagValue
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt 
        - TestingNameCodeDeploy
        - Outputs.CodeDeployTrustRoleARN
  TestingName:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStore
        Type: S3
      RoleArn: !Join 
        - ''
        - - 'arn:aws:iam::'
          - !Ref 'AWS::AccountId'
          - ':role/'
          - !Ref CodePipelineRole
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: MyApp
              Configuration:
                ConnectionArn: "arn:aws:codestar-connections:us-east-1:448992612150:connection/d811f751-5976-4af3-9d79-e15a763a08bd"
                FullRepositoryId: "pawanrai852/CodeDeployRepository"
                BranchName: "main"
              RunOrder: 1
        - Name: Build
          Actions:
            - InputArtifacts:
                - Name: MyApp
              Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                  - Name: MyPipeline-BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildJavaProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - InputArtifacts:
                - Name: MyPipeline-BuildArtifact
              Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CodeDeploy
              OutputArtifacts: []
              Configuration:
                ApplicationName: !Ref TestingAppName
                DeploymentGroupName: !Ref TestingAppGroupName
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Fn::Join:
          - ''
          - - codepipeline-
            - Ref: AWS::Region
            - "-"
            - Ref: AWS::AccountId
# Outputs:
#   CodeBuildURL:
#     Value:
#       Fn::Join:
#       - ''
#       - - https://console.aws.amazon.com/codebuild/home?region=
#         - Ref: AWS::Region
#         - "#/projects/"
#         - Ref: CodeBuildJavaProject
#         - "/view"
#     Description: CodeBuild URL
#   CodeCommitURL:
#     Value:
#       Fn::Join:
#       - ''
#       - - https://console.aws.amazon.com/codecommit/home?region=
#         - Ref: AWS::Region
#         - "#/repository/"
#         - Ref: AWS::StackName
#         - "/browse/HEAD/--/"
#     Description: Git Repository URL
#   CodeDeployURL:
#     Value:
#       Fn::Join:
#       - ''
#       - - https://console.aws.amazon.com/codedeploy/home?region=
#         - Ref: AWS::Region
#         - "#/deployments/"
#     Description: CodeDeploy URL
#   CloneUrlSsh:
#     Value:
#       Fn::Join:
#       - ''
#       - - 'git clone '
#         - Fn::GetAtt:
#           - CodeCommitJavaRepo
#           - CloneUrlSsh
#         - ''
#     Description: Git command for CodeCommit repository
#   CodePipelineURL:
#     Value:
#       Fn::Join:
#       - ''
#       - - https://console.aws.amazon.com/codepipeline/home?region=
#         - Ref: AWS::Region
#         - "#/view/"
#         - Ref: CodePipelineStack
#     Description: CodePipeline URL